### ISSUE TITLE
I get the Error: Cannot find module './userStory.json'

### ISSUE THREAD

**Issue by ghost** [happyfreemo69/pt2taiga#1]
Hi, 
I am trying to do the same, but I am stuck at this error.
On a local taiga install, when doing :
node convert -i 0.json

any clue ?

Thanks

**Comment by mpech** [comment]
unfortunately it has been a while now. Maybe 0.json does not look like the same as it used when I used it.
Mine (I somehow have a json from the past) looks like (after parsing):
```
[
{ id: 106313824,
  created_at: '2015-10-22T15:31:49Z',
  updated_at: '2016-03-08T18:43:13Z',
  story_type: 'bug',
  name: '[Vote] Faute d\'ortho',
  description: 'Gérer les vote**s**. A corriger.\nVoir PJ\n',
  current_state: 'accepted',
  requested_by_id: 1827944,
  labels: 
   [ { id: 13088218,
       project_id: 1452050,
       kind: 'label',
       name: 'bo',
       created_at: '2015-10-20T07:54:49Z',
       updated_at: '2015-10-20T07:54:49Z' } ],
  tasks: [],
  comments: 
   [ { kind: 'comment',
       id: 115530054,
       person_id: 1827944,
       created_at: '2015-10-22T15:31:50Z',
       updated_at: '2015-10-22T15:31:50Z',
       story_id: 106313824 },
     { kind: 'comment',
       id: 115609036,
       text: 'c\'est corrigé sur dev, la prochaine version',
       person_id: 1827946,
       created_at: '2015-10-23T06:12:13Z',
       updated_at: '2015-10-23T06:12:13Z',
       story_id: 106313824 } ] }
]
```

maybe could you attach the error you encounter?

**Comment by ghost** [comment]
I need to create a file userStory.json with that kind of content ?
My file 0.json (export from pivotal) looks just the same as yours, but I don't get the link between my file 0.json and the userStory.json file that does not exist in my folders.

The complete error is 

`Error: Cannot find module './userStory.json'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/taiga/import/taiga/taigaUploader.js:15:36)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
`

**Comment by ghost** [comment]
example of json export from pivotal 

{
  "kind": "story",
  "id": 151303267,
  "created_at": "2017-10-09T15:20:24Z",
  "updated_at": "2017-10-09T15:21:10Z",
  "story_type": "feature",
  "name": "categories : create a new field img in model",
  "description": "one field for icon ( fa-...) already exits\nand one field with the img for the \"discover the available dataset\" in homepage",
  "current_state": "unscheduled",
  "requested_by_id": 1883972,
  "url": "https://www.pivotaltracker.com/story/show/151303267",
  "project_id": 1504163,
  "owner_ids": [
    2175475
  ],
  "labels": [
    {
      "id": 15336491,
      "project_id": 1504163,
      "kind": "label",
      "name": "usability",
      "created_at": "2016-07-22T12:35:03Z",
      "updated_at": "2016-07-22T12:35:03Z"
    }
  ],
  "owned_by_id": 2175475
}

**Comment by mpech** [comment]
> Error: Cannot find module './userStory.json' at Function.Module._resolveFilename 

Yes, apologies, I think I forgot/missed to version it...

According to 
```
var storyTemplate = JSON.stringify(require('./userStory.json'), null, 1);
```
userStory.json should be equal to [the userStory template](https://taigaio.github.io/taiga-doc/dist/api.html#user-stories-create) 
idem a subset of
```
{
        "assigned_to": null,
        "backlog_order": 2,
        "blocked_note": "blocking reason",
        "client_requirement": false,
        "description": "Implement API CALL",
        "is_blocked": false,
        "is_closed": true,
        "kanban_order": 37,
        "milestone": null,
        "points": {
            "1": 4,
            "2": 3,
            "3": 2,
            "4": 1
        },
        "project": 1,
        "sprint_order": 2,
        "status": 2,
        "subject": "Customer personal data",
        "tags": [
            "service catalog",
            "customer"
        ],
        "team_requirement": false,
        "watchers": []
    }
```

probably  for you userStory.json == 
(I am not at work and even at work I probably don't have the file anymore)
```

{
        "assigned_to": null,
        "milestone": null,
        "project": 1,
    }
```

Anyway everything is in https://github.com/happyfreemo69/pt2taiga/blob/master/taiga/taigaUploader.js
uploader.upload

**Comment by ghost** [comment]
Thanks. It helped us.

On top of that, to make it work :
We commented port:8000 in taigaAPI.js as we are running taiga on port 80.
and in taigauploarder.js :
taigaStatus were set to the user story status of the target project.
We have commented task.milestone as we didn't need it.
return fs.exists(OUTPUT_FOLDER+task.id, function(y){ 
was changed to 
return fs.exists(OUTPUT_FOLDER+'uploaded_'++task.id, function(y){

var fname = OUTPUT_FOLDER+iTask.id; 
was changed to 
var fname = OUTPUT_FOLDER+'uploaded_'+iTask.id;

and finally, userStory.json was set to : 

> {
        "assigned_to": null,
        "blocked_note": "blocking reason",
        "client_requirement": false,
        "description": "Test to create stories from shell with import script",
        "is_blocked": false,
        "is_closed": true,
        "milestone": null,
        "project": 10,
                "status": 57,
                "subject": "Story created via shell import ",
                "tags": [
            "service catalog",
            "customer"
        ],
        "team_requirement": false,
        "watchers": []
}

And that's it

Many thanks for that !

**Comment by mpech** [comment]
glad it worked for you.
(and taiga is (admittedly opinionated) a great choice, we are still using it, a few flaws but overall a great tool!)
